add_cxxflags("--debug")
set_kind("binary")
set_languages("c++17")
add_includedirs("/Users/bopeng/c/tools/v8/v8")
add_includedirs("/Users/bopeng/c/tools/v8/v8/include")
-- add_linkdirs("/Users/bopeng/c/tools/v8/v8/out.gn/x64.release.sample/obj/")
add_linkdirs("/Users/bopeng/c/tools/v8/lib")
-- https://www.mail-archive.com/v8-dev@googlegroups.com/msg160061.html
-- add_links("v8_monolith_disable_pointer_compression_debug")
-- add_links("v8_monolith_disable_pointer_compression")
add_links("v8_monolith")
add_defines("V8_COMPRESS_POINTERS")
set_rundir("$(projectdir)/js")
target("hello")
	add_files("helloworld.cc") 
target("shell")
	add_files("shell.cc") 
target("process")
	add_files("process.cc") 
target("inspector")
	add_files("inspector.cc") 
target("inspector-console-delegate")
	add_files("inspector-console-delegate.cc") 