add_cxxflags("--debug")
set_kind("binary")
set_languages("c++11")
add_includedirs("/Users/bopeng/c/tools/v8/include")
add_linkdirs("/Users/bopeng/c/tools/v8lib")
target("hello")
	add_links("v8_monolith")
	add_files("helloworld.cc") 
target("shell")
	-- https://www.mail-archive.com/v8-dev@googlegroups.com/msg160061.html
	-- add_links("v8_monolith_disable_pointer_compression_debug")
	add_links("v8_monolith")
	add_defines("V8_COMPRESS_POINTERS")
	-- add_links("v8_monolith_disable_pointer_compression")
	add_files("shell.cc") 